#!/usr/bin/env bun
/**
 * Writes GitHub release notes for a fork release tag with a Z.ai model
 * (port of the inline release-notes step of the Crush fork's release workflow).
 *
 * The model sees the commits since the previous fork release, without the
 * commits that the upstream base release already contains. The notes link to
 * that upstream release instead.
 */
import * as path from "node:path";
import { parseArgs } from "node:util";
import { type } from "@oh-my-pi/omptype";
import * as prompt from "@oh-my-pi/pi-utils/prompt";
import { $ } from "bun";
import { parseReleaseVersion, REPO_ROOT } from "./fork-version";
import { FORK_REPOSITORY } from "./release-layout";
import releaseNotesPrompt from "./release-notes-prompt.md" with { type: "text" };

const ZAI_CHAT_COMPLETIONS_URL = "https://api.z.ai/api/coding/paas/v4/chat/completions";
const UPSTREAM_REPOSITORY = "can1357/oh-my-pi";
const USER_SEPARATOR = "<!-- USER -->";
const COMMIT_SEPARATOR = "\n---END COMMIT---\n";
const MAX_COMMITS = 500;
const MAX_COMPLETION_TOKENS = 8192;
const REQUEST_TIMEOUT_MS = 5 * 60_000;

const GitHubReleaseList = type({ tagName: "string" }).array();
const ChatCompletion = type({
	"choices?": type({ "finish_reason?": "string | null", "message?": { "content?": "string | null" } }).array(),
});

const USAGE = `Usage:
  bun scripts/taoeffect/release-notes.ts <tag> [--repo <owner/name>] [--out <file>]

Writes release notes for the fork release <tag> (v<upstream>-taoeffect.<n>) to
--out (default: dist/release-notes.md). Needs the environment variables
ZAI_API_KEY and RELEASE_MODEL, a clone with the full history and tags, and an
authenticated gh for the GitHub release lookup in --repo (default: ${FORK_REPOSITORY}).

The previous release is the newest GitHub release of --repo whose tag is an
ancestor of <tag>, else the newest merged v*-taoeffect.* tag. Commits that the
upstream base tag v<upstream> contains are left out; the script fetches that
tag from ${UPSTREAM_REPOSITORY} when the clone lacks it.`;

export interface CommitLog {
	text: string;
	omitted: number;
}

export interface CommitLogLimits {
	maxMessageChars: number;
	maxTotalChars: number;
}

const DEFAULT_COMMIT_LOG_LIMITS: CommitLogLimits = { maxMessageChars: 2_000, maxTotalChars: 60_000 };

/**
 * Keeps the newest commit messages (`messages` is newest first) that fit in the
 * size budget, each cut to a maximum length. `totalCommits` counts every commit
 * in the range, including the ones `git log --max-count` already dropped.
 */
export function boundCommitMessages(
	messages: readonly string[],
	totalCommits: number,
	limits: CommitLogLimits = DEFAULT_COMMIT_LOG_LIMITS,
): CommitLog {
	const kept: string[] = [];
	let size = 0;
	for (const message of messages) {
		const bounded =
			message.length > limits.maxMessageChars ? `${message.slice(0, limits.maxMessageChars)}…` : message;
		size += bounded.length + COMMIT_SEPARATOR.length;
		if (size > limits.maxTotalChars) break;
		kept.push(bounded);
	}
	return { text: kept.join(COMMIT_SEPARATOR), omitted: Math.max(totalCommits, messages.length) - kept.length };
}

function renderReleaseNotesPrompt(context: prompt.TemplateContext): { system: string; user: string } {
	const separator = releaseNotesPrompt.indexOf(USER_SEPARATOR);
	return {
		system: releaseNotesPrompt.slice(0, separator).trim(),
		user: prompt.render(releaseNotesPrompt.slice(separator + USER_SEPARATOR.length), context).trim(),
	};
}

function formatReleaseNotes(notes: string, upstreamTag: string, model: string): string {
	const upstreamRelease = `https://github.com/${UPSTREAM_REPOSITORY}/releases/tag/${upstreamTag}`;
	const sections = [
		notes,
		`Based on upstream oh-my-pi [${upstreamTag}](${upstreamRelease}).`,
		`Release notes generated by ${model}.`,
	];
	return `${sections.filter(Boolean).join("\n\n")}\n`;
}

async function requestReleaseNotes(options: {
	apiKey: string;
	model: string;
	system: string;
	user: string;
}): Promise<string> {
	const response = await fetch(ZAI_CHAT_COMPLETIONS_URL, {
		method: "POST",
		headers: { Authorization: `Bearer ${options.apiKey}`, "Content-Type": "application/json" },
		body: JSON.stringify({
			model: options.model,
			temperature: 0.2,
			// GLM models spend most tokens on reasoning (one test run: 1633 of 1936), so Crush's 2000 is too tight.
			max_tokens: MAX_COMPLETION_TOKENS,
			messages: [
				{ role: "system", content: options.system },
				{ role: "user", content: options.user },
			],
		}),
		signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
	});
	if (!response.ok) {
		throw new Error(`Z.ai release notes request failed with ${response.status}: ${await response.text()}`);
	}
	const completion = ChatCompletion(await response.json());
	if (completion instanceof type.errors) throw new Error(`Unexpected Z.ai response: ${completion.summary}`);
	const choice = completion.choices?.[0];
	if (choice?.finish_reason === "length") {
		throw new Error(
			`Z.ai stopped at the ${MAX_COMPLETION_TOKENS}-token limit before the release notes were complete`,
		);
	}
	return (choice?.message?.content ?? "")
		.replace(/^```(?:markdown)?\s*/i, "")
		.replace(/\s*```$/i, "")
		.trim();
}

function git(args: readonly string[]) {
	return $`git ${args}`.cwd(REPO_ROOT).quiet().nothrow();
}

async function gitText(args: readonly string[]): Promise<string> {
	const result = await git(args);
	if (result.exitCode !== 0) {
		throw new Error(
			`git ${args.join(" ")} failed with exit code ${result.exitCode}: ${result.stderr.toString().trim()}`,
		);
	}
	return result.text();
}

async function hasTag(tag: string): Promise<boolean> {
	return (await git(["rev-parse", "--verify", "--quiet", `refs/tags/${tag}^{commit}`])).exitCode === 0;
}

function isForkReleaseTag(tag: string): boolean {
	if (!tag.startsWith("v")) return false;
	try {
		parseReleaseVersion(tag.slice(1));
		return true;
	} catch {
		return false;
	}
}

async function findPreviousRelease(tag: string, repo: string): Promise<string | undefined> {
	const releaseList = await $`gh release list --repo ${repo} --exclude-drafts --limit 100 --json tagName`
		.quiet()
		.nothrow();
	const releases = releaseList.exitCode === 0 ? GitHubReleaseList(releaseList.json()) : undefined;
	if (releases === undefined || releases instanceof type.errors) {
		const reason = releases?.summary ?? releaseList.stderr.toString().trim();
		console.error(`Could not list the GitHub releases of ${repo}; using merged tags instead. ${reason}`);
	} else {
		for (const { tagName } of releases) {
			if (tagName === tag || !isForkReleaseTag(tagName) || !(await hasTag(tagName))) continue;
			const ancestor = await git(["merge-base", "--is-ancestor", `refs/tags/${tagName}`, `refs/tags/${tag}`]);
			if (ancestor.exitCode === 0) return tagName;
		}
	}

	const mergedTags = await gitText([
		"tag",
		"--merged",
		`refs/tags/${tag}`,
		"--sort=-creatordate",
		"--list",
		"v*-taoeffect.*",
	]);
	return mergedTags.split("\n").find(candidate => candidate !== tag && isForkReleaseTag(candidate));
}

async function readCommitLog(tag: string, excludedTags: readonly string[]): Promise<CommitLog> {
	const range = [`refs/tags/${tag}`, ...excludedTags.map(excluded => `^refs/tags/${excluded}`)];
	const total = Number((await gitText(["rev-list", "--count", ...range])).trim());
	const log = await gitText(["log", "-z", "--format=%B", `--max-count=${MAX_COMMITS}`, ...range]);
	const messages = log
		.split("\0")
		.map(message => message.trim())
		.filter(Boolean);
	return boundCommitMessages(messages, total);
}

export interface ReleaseNotesOptions {
	tag: string;
	repo: string;
	apiKey: string;
	model: string;
}

/** Returns the Markdown release notes for the fork release `tag`. */
export async function generateReleaseNotes({ tag, repo, apiKey, model }: ReleaseNotesOptions): Promise<string> {
	if (!isForkReleaseTag(tag)) throw new Error(`Expected a fork release tag like v18.4.9-taoeffect.1, got ${tag}`);
	if (!(await hasTag(tag))) throw new Error(`The local clone has no tag ${tag}`);

	const upstreamTag = `v${parseReleaseVersion(tag.slice(1)).base.version}`;
	if (!(await hasTag(upstreamTag))) {
		console.log(`Fetching ${upstreamTag} from ${UPSTREAM_REPOSITORY}`);
		const upstreamUrl = `https://github.com/${UPSTREAM_REPOSITORY}.git`;
		await gitText(["fetch", "--no-tags", upstreamUrl, `refs/tags/${upstreamTag}:refs/tags/${upstreamTag}`]);
	}
	const previous = await findPreviousRelease(tag, repo);
	const excludedTags = previous ? [previous, upstreamTag] : [upstreamTag];
	console.log(`Release notes cover ${tag} without ${excludedTags.join(" and ")}`);
	const commits = await readCommitLog(tag, excludedTags);
	if (commits.omitted > 0) console.log(`Left out the ${commits.omitted} oldest commits to bound the request size`);

	const { system, user } = renderReleaseNotesPrompt({
		tag,
		previous: previous ?? `upstream oh-my-pi ${upstreamTag}`,
		commits: commits.text,
		omitted: commits.omitted,
	});
	const notes = await requestReleaseNotes({ apiKey, model, system, user });
	return formatReleaseNotes(notes, upstreamTag, model);
}

async function main(): Promise<void> {
	const { values, positionals } = parseArgs({
		args: process.argv.slice(2),
		allowPositionals: true,
		options: {
			repo: { type: "string", default: FORK_REPOSITORY },
			out: { type: "string", default: path.join(REPO_ROOT, "dist", "release-notes.md") },
			help: { type: "boolean", short: "h", default: false },
		},
	});
	if (values.help) {
		console.log(USAGE);
		return;
	}
	if (positionals.length !== 1) throw new Error(`expected exactly one <tag> argument\n\n${USAGE}`);
	const apiKey = Bun.env.ZAI_API_KEY;
	const model = Bun.env.RELEASE_MODEL;
	if (!apiKey) throw new Error("ZAI_API_KEY is required");
	if (!model) throw new Error("RELEASE_MODEL is required");
	const notes = await generateReleaseNotes({ tag: positionals[0], repo: values.repo, apiKey, model });
	const outPath = path.resolve(values.out);
	await Bun.write(outPath, notes);
	console.log(`Wrote ${outPath}`);
}

if (import.meta.main) {
	try {
		await main();
	} catch (error) {
		console.error(`release-notes: ${error instanceof Error ? error.message : String(error)}`);
		process.exit(1);
	}
}
